services:
  db:
    container_name: db
    build: ./app/database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  test:
    container_name: test
    build: 
      context: ./app
      dockerfile: Dockerfile-test
volumes:
  db:
    driver: local