# syntax=docker/dockerfile:1

FROM python:3.9-alpine

WORKDIR /python-test

COPY requirements.txt requirements.txt

RUN apk add build-base && \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    python -m pip install "pymongo[srv]" && \
    apk --purge del .build-deps

COPY . /python-test/

ENV APP_SETTINGS="config.Config"
ENV SQLALCHEMY_DATABASE_URI="postgresql://postgres:postgres@db:5432/main"
ENV SQLALCHEMY_DATABASE_URI_TEST="postgresql://postgres:postgres@db:5432/test"

CMD ["python", "-m", "pytest"]