"""empty message

Revision ID: ecf2f1bced2c
Revises: d48fdc20a7ac
Create Date: 2022-09-25 19:02:52.333714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf2f1bced2c'
down_revision = 'd48fdc20a7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisor', sa.Column('financial_independence', sa.Boolean(), nullable=True))
    op.add_column('advisor', sa.Column('smb', sa.Boolean(), nullable=True))
    op.add_column('advisor', sa.Column('retirement', sa.Boolean(), nullable=True))
    op.add_column('advisor', sa.Column('education', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advisor', 'education')
    op.drop_column('advisor', 'retirement')
    op.drop_column('advisor', 'smb')
    op.drop_column('advisor', 'financial_independence')
    # ### end Alembic commands ###
