"""empty message

Revision ID: fb6e711a334b
Revises: 5c6d8879cca7
Create Date: 2022-09-25 22:39:37.136909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6e711a334b'
down_revision = '5c6d8879cca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(), nullable=True),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('advisor', 'financial_independence')
    op.drop_column('advisor', 'education')
    op.drop_column('advisor', 'smb')
    op.drop_column('advisor', 'retirement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisor', sa.Column('retirement', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('advisor', sa.Column('smb', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('advisor', sa.Column('education', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('advisor', sa.Column('financial_independence', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('specialization')
    # ### end Alembic commands ###
